PINVmat<-function(x,maxTriess=3000,intervall=30)
{
  write.table(x,file="x.txt",col.names=F,row.names=F)
  linkE<-noquote(paste(getwd(),"x.txt",sep="/"))
  link<-noquote(getwd())
  R.matlab::Matlab$startServer()
  matlab <- R.matlab::Matlab(port = 9999)
  R.matlab::setOption(matlab, "readResult/maxTries", maxTriess)
  R.matlab::setOption(matlab, "readResult/interval", intervall)
  open(matlab)
  R.matlab::setVariable(matlab,linkE = linkE)
  R.matlab::setVariable(matlab,link = link)
  R.matlab::evaluate(matlab, "x = dlmread(linkE);")
  R.matlab::evaluate(matlab, "xinv = pinv(x);")
  R.matlab::evaluate(matlab, "folder = link;")
  R.matlab::evaluate(matlab, "dlmwrite('xinv.txt',xinv,'delimiter',' ');")
  close(matlab)
  xinv<-read.table("xinv.txt");xinv<-as.matrix(xinv);colnames(xinv)<-c()
  file.remove("x.txt","xinv.txt")
  return(xinv)
}
